# Generated by Django 4.1.4 on 2023-01-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('hair_color', models.CharField(max_length=30)),
                ('eye_color', models.CharField(max_length=30)),
                ('birth_year', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('homeworld', models.URLField()),
                ('films', models.CharField(max_length=300)),
                ('species', models.CharField(max_length=30)),
                ('vehicles', models.CharField(max_length=300)),
                ('starships', models.CharField(max_length=300)),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
